### ver menu
GET http://localhost:3000/api/menu
content-type: 'json'


### criar pedido
POST http://localhost:3000/api/order
Content-Type: application/json

{
    "userId" : 1,
    "product" : "Latte",
    "variation" : "Vanilla"
}


### ver detalhes
GET http://localhost:3000/api/orders
Content-Type: application/json

{
    "userId" : 1
}
### ver detalhes
PUT http://localhost:3000/api//order/status/7
Content-Type: application/json
role: manager

{
    "userId" : 1
}