name: Process Candidate Evaluations

on:
  push:
    branches: [ master ]
  workflow_dispatch:   # Allow manual triggering

# Explicitly set permissions for the GITHUB_TOKEN
permissions:
  contents: write  # This gives write permission to the workflow for repository contents

jobs:
  process-evaluations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper README updates
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run summary script
        run: |
          python .github/actions/summarize_grades.py
      
      - name: Commit changes if README is updated
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update candidates grade summary"
          file_pattern: "candidates.md"